language: node_js
node_js:
  - 'stable'
script:
  - npm test
deploy:
  - provider: elasticbeanstalk
    app: open-vitae
    env: open-vitae
    region: ap-northeast-1
    bucket_name: elasticbeanstalk-ap-northeast-1-047651431481
    bucket_path: open-vitae
    access_key_id:
      secure: C8L4jvd+pbdpElUn9xB6pc289lLQiyazmKy6Q6I/aGsSMBd8JGV/Jdw37HfKw+t3MZmVzsbhAQW1J8thk6kL40v1EjWMk8vwOVyOoyujE9RcvgnTd6bqcypRmASsDwSt4cqVxu3wXiA+eYbd5w6rCH9O4Dtvv3y9xL+NILsEDQ7pHMK5sWxJoc07z0bXLxQN9YaNajPLfRNRbJjoSLmn+qNYh0hpeP9XmPbOP3Ms9YqOAudaqaaZY9XvAYLdWc0LwAUdT5B/M9pavTMvlJ55pa4bckDGQCGnG9NAsCqD8x9tULtBzq0JnR8HnY9gV4jK+5O6f3fGYNxIS++Stt/jVDuZD1VjHmwSbFVcoXr4kvrSmX2QRccP2wReN/768Fz3HZOmcvUkq5p10JccELuRTyGxdPyni+wrCSvhgyQDd83e/mZkosi9pC39Rulth7ZsE5AVTlWwhlgo3uMmtGH1sav0L51c3eCi9SRml5nPRcO4Fvf/+ODvRupHRJosiMiQM5rZLleRbn3bN3PSXy8hW8v9R+FbvYUjYJjGJCl2H34uGqfuF9UbmOOCHfrvE8t5vm6B2I5jbsrOrGzY1Z0VF2UEn0tR6KXGMSc6tibQgDX99EPOwo08QnahU3oRn74ZDUM9bJa/ahaWjGvQ2i41Ngs/ckF8pIf6Hl3HeT3ErZs=
    secret_access_key:
      secure: cUvw22PZJ3fhR5BR2mu65p1Tamc8FfyoyKF7r8cGU3yXQM/Temduqk4k3BYL4kaXTgZVoVQcRXKCfEXhxx62xt0Wa/TqiEdu7OvXxbWoTPqzKwacZJdnKZjAeKpBdjIv1LjwM8Dxs+XzR2U6iWhzB1N8dukaM0C5dqngqOkszfnL7VX4bhzUfeEWDeir7ygd56wpSSbLA26kPn/wJ6MsV74b7Ai9xyD5SiiSwlSPzZQ1ITrXlqXYa9TdxqfQGA/fu9pY5elVGF7vo5prPFVXf7cuOGau2J8r/Afr4TsxFUf4Mq9ea+1vVbNX+ghw3kiXDFRHFR4fB7mPGyNKPzrQZr4PdnypwzffS1EVDxPkt1FwBmOG+1tZmyztPsnz4PJKInHzSDdSm5D8VCUvbdQQBhCz9I0jTXQuLVqfbg+++FRaIvtn6IeiJJMgZtK5wUAiTFVignxQzVW7v7/1kTwl1HEdObAo9DLtD3dnnezps8ZeKju0Blx+/iTPc0YRLxz/4gYX+FKAUulVPydZpQFYvAoE8svuVtZcU9iBSh2j66H5NEzQx+Jx0VgXYGXrilQoKkMtsMroYEY8e0dLpY+uCfAdH/RO1MU25vm7/Eb6jQmvOknuP1z/DOV53vEogxdgDCRYpgo7hHNIYIY48m6ye2U3Wl+LfvrWjKDDVHnwAoA=